name: Autowiki
on:
  schedule:
  - cron: "5 4 * * *"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  autowiki:
    runs-on: ubuntu-latest
    steps:
    - name: "Check for AUTOWIKI_USERNAME"
      id: secrets_set
      env:
        ENABLER_SECRET: ${{ secrets.AUTOWIKI_USERNAME }}
      run: |
        unset SECRET_EXISTS
        if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
        echo "SECRETS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT
    - name: Checkout
      if: steps.secrets_set.outputs.SECRETS_ENABLED
      uses: actions/checkout@v3
    - name: Set BYOND version
      run: |
        source ./dependencies.sh
        echo "BYOND_MAJOR=$BYOND_MAJOR" >> $GITHUB_ENV
        echo "BYOND_MINOR=$BYOND_MINOR" >> $GITHUB_ENV
    - name: Restore BYOND cache
      uses: actions/cache@v3
      with:
        path: ~/BYOND
        key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
    - name: Download and unzip BYOND
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        max_attempts=3
        attempt=1
        minor=$BYOND_MINOR
        while (( attempt <= max_attempts )); do
          echo "Download and unzip BYOND $BYOND_MAJOR.$minor"
          mkdir -p "$HOME/BYOND-${BYOND_MAJOR}.${minor}"
          cd $HOME/BYOND-${BYOND_MAJOR}.${minor}
          curl -L "https://web.archive.org/web/20250322230727/https://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${minor}_byond.zip" -o byond.zip -A "CMSS13/1.0 Continuous Integration"
          if [[ $? -ne 0 || ! -s byond.zip ]]; then
            echo "Download error"
          elif unzip -o byond.zip; then
            break
          else
            ((attempt++))
            ((minor++))
            echo "BYOND_MINOR=$minor" >> $GITHUB_ENV
            if (( attempt > max_attempts )); then
              exit 1
            fi
          fi
        done
        rm byond.zip
        echo "Success unzip"
    - name: Install BYOND
      run: |
        echo "Install BYOND"
        cd "$HOME/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}/byond"
        make here
    - name: Install rust-g
      if: steps.secrets_set.outputs.SECRETS_ENABLED
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update || true
        sudo apt install -o APT::Immediate-Configure=false zlib1g-dev:i386 libssl-dev:i386
        bash tools/ci/install_rust_g.sh
    - name: Compile and generate Autowiki files
      if: steps.secrets_set.outputs.SECRETS_ENABLED
      run: |
        source $HOME/BYOND/byond/bin/byondsetup
        tools/build/build --ci autowiki
    - name: Run Autowiki
      if: steps.secrets_set.outputs.SECRETS_ENABLED
      env:
        USERNAME: ${{ secrets.AUTOWIKI_USERNAME }}
        PASSWORD: ${{ secrets.AUTOWIKI_PASSWORD }}
      run: |
        cd tools/autowiki
        npm install
        cd ../..
        node tools/autowiki/autowiki.js data/autowiki_edits.txt data/autowiki_files/
